# Generated by Django 6.0.1 on 2026-01-08 18:36

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viudo(a)')], max_length=1)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('provincia', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('tipo_vivienda', models.CharField(choices=[('P', 'Propia'), ('A', 'Alquilada'), ('F', 'Familiar')], max_length=1)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('nombre_conyuge', models.CharField(blank=True, max_length=200, null=True)),
                ('tiene_hijos', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=api.models.employee_directory_path)),
                ('fecha_ingreso_inicial', models.DateField()),
                ('fotocopia_ci', models.FileField(blank=True, null=True, upload_to=api.models.employee_directory_path)),
                ('curriculum_vitae', models.FileField(blank=True, null=True, upload_to=api.models.employee_directory_path)),
                ('certificado_antecedentes', models.FileField(blank=True, null=True, upload_to=api.models.employee_directory_path)),
                ('fotocopia_luz_agua_gas', models.FileField(blank=True, null=True, upload_to=api.models.employee_directory_path)),
                ('croquis_domicilio', models.FileField(blank=True, null=True, upload_to=api.models.employee_directory_path)),
                ('fotocopia_licencia_conducir', models.FileField(blank=True, null=True, upload_to=api.models.employee_directory_path)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cargo')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departamento')),
                ('jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='api.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('plazo_fijo', 'Plazo Fijo'), ('indefinido', 'Indefinido'), ('eventual', 'Eventual'), ('temporal', 'Temporal')], max_length=20)),
                ('tipo_trabajador', models.CharField(choices=[('eventual', 'Eventual'), ('permanente', 'Permanente'), ('consultor', 'Consultor'), ('pasante', 'Pasante')], max_length=20)),
                ('contrato_fiscal', models.CharField(choices=[('avicola', 'Avicola Rolon S.R.L'), ('ovoplus', 'Ovoplus S.R.L'), ('soya_cruz', 'Soya Cruz S.R.L'), ('opticargo', 'Opticargo S.R.L'), ('rau_rimski', 'RAU Rimski Cesar Ariel Rolon Rios'), ('rau_nashira', 'RAU Nashira Orellana Rolon'), ('rau_silvia', 'RAU Silvia Catusha Rolon Rios')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_fin_pactada', models.DateField(blank=True, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jornada_laboral', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('turnos', 'Turnos')], max_length=20)),
                ('estado_contrato', models.CharField(choices=[('vigente', 'Vigente'), ('finalizado', 'Finalizado'), ('anulado', 'Anulado')], default='vigente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='api.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('posgrado', 'Posgrado'), ('curso', 'Curso'), ('otro', 'Otro')], max_length=20)),
                ('carrera', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('concluido', 'Concluido'), ('cursando', 'Cursando'), ('inconcluso', 'Inconcluso')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='api.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('parentesco', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('esposo/a', 'Esposo(a)'), ('hermano/a', 'Hermano(a)'), ('hijo/a', 'Hijo(a)'), ('otro', 'Otro')], max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='api.empleado')),
            ],
        ),
    ]
