# Generated by Django 6.0.1 on 2026-01-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_empleado_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='jefe_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_liderados', to='api.empleado'),
        ),
    ]
