# Generated by Django 6.0.1 on 2026-01-07 20:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_empleado_contrato_estudio_familiar_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.employee_directory_path),
        ),
    ]
