# Generated by Django 6.0.1 on 2026-01-09 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_empleado_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('tipo_permiso', models.CharField(choices=[('trabajo', 'Trabajo'), ('personal', 'Personal'), ('hora_almuerzo', 'Hora Almuerzo')], max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('hora_salida', models.TimeField()),
                ('hora_regreso', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departamento')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='api.empleado')),
                ('jefe_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aprobados_jefe', to='api.empleado')),
            ],
        ),
    ]
