# Generated by Django 6.0.1 on 2026-01-09 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_permiso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='permiso',
            name='jefe_departamento',
        ),
        migrations.AddField(
            model_name='permiso',
            name='aprobador_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_a_aprobar', to='api.empleado'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='comentario_aprobador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
