# Generated by Django 6.0.1 on 2026-01-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_permiso_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='fecha_solicitud',
            field=models.DateField(),
        ),
    ]
