# Generated by Django 6.0.1 on 2026-01-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_create_porteria_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('tipo_hora_extra', models.CharField(choices=[('compensacion', 'Compensación de Hrs Extra'), ('horas_extras', 'Horas Extras')], max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('comentario_aprobador', models.TextField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_extras_a_aprobar', to='api.empleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extras', to='api.empleado')),
            ],
        ),
    ]
