# Generated by Django 6.0.1 on 2026-01-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_horaextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('es_medio_dia', models.BooleanField(default=False, help_text='Si es True, cuenta como 0.5 días')),
                ('dias_calculados', models.DecimalField(decimal_places=1, help_text='Días a descontar del saldo', max_digits=5)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('comentario_aprobador', models.TextField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_a_aprobar', to='api.empleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacacion', to='api.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='VacacionPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del contrato o ciclo')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha fin del contrato o renovación', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_vacacion', to='api.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='VacacionMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('inicio_contrato', 'Inicio/Renovación Contrato'), ('acumulacion_anual', 'Acumulación Anual'), ('consumo', 'Consumo (Solicitud)'), ('pago', 'Pago en Efectivo'), ('ajuste', 'Ajuste Manual'), ('traspaso', 'Traspaso de Saldo')], max_length=50)),
                ('dias', models.DecimalField(decimal_places=2, help_text='Valor positivo aumenta saldo, negativo resta', max_digits=6)),
                ('detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_vacacion', to='api.empleado')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='api.solicitudvacacion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.vacacionperiodo')),
            ],
        ),
    ]
