# Generated by Django 6.0.1 on 2026-01-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_solicitudvacacion_vacacionperiodo_vacacionmovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso_vigente',
            field=models.DateField(blank=True, help_text='Fecha de ingreso del contrato vigente', null=True),
        ),
    ]
