# Generated by Django 6.0.1 on 2026-01-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_empleado_fecha_ingreso_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='feature_vacaciones',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='vacaciones_guardadas',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Días acumulados de gestiones anteriores', max_digits=5),
        ),
    ]
