# Generated by Django 6.0.1 on 2026-01-13 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_empleado_feature_vacaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='vacaciones_guardadas',
        ),
        migrations.CreateModel(
            name='VacacionGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.DecimalField(decimal_places=1, max_digits=5)),
                ('gestion', models.CharField(blank=True, help_text='Gestión o motivo (ej. 2022-2023)', max_length=50, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones_guardadas_list', to='api.empleado')),
            ],
        ),
    ]
