# Generated by Django 6.0.1 on 2026-01-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_empleado_vacaciones_guardadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudvacacion',
            name='estado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('anulado', 'Anulado')], default='aprobado', max_length=20),
        ),
    ]
