# Generated by Django 6.0.1 on 2026-01-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_solicitudvacacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacacion',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_vacacion', to='api.contrato'),
        ),
        migrations.AddField(
            model_name='vacacionguardada',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_guardadas', to='api.contrato'),
        ),
        migrations.AddField(
            model_name='vacacionmovimiento',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_vacacion', to='api.contrato'),
        ),
    ]
