# Generated by Django 6.0.1 on 2026-01-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_solicitudvacacion_contrato_vacacionguardada_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
