# Generated by Django 6.0.1 on 2026-01-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_contrato_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='codigo',
        ),
    ]
