# Generated by Django 6.0.1 on 2026-01-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_contrato_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacacionperiodo',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='VacacionMovimiento',
        ),
        migrations.DeleteModel(
            name='VacacionPeriodo',
        ),
    ]
