# Generated by Django 6.0.1 on 2026-01-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_vacacionperiodo_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacionguardada',
            name='fecha',
            field=models.DateField(blank=True, help_text='Fecha a la que corresponde el movimiento', null=True),
        ),
    ]
